services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python src/main.py"
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    restart:
      always

  db:
    image: postgres:17.0
    env_file:
      - .env
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart:
      always