"""Added fields

Revision ID: 10a12ee0db7a
Revises: 
Create Date: 2024-12-12 01:50:51.630846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a12ee0db7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_time_given', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('is_reffed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_possible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_possible')
    op.drop_column('users', 'is_reffed')
    op.drop_column('users', 'last_time_given')
    # ### end Alembic commands ###
